# インフラストラクチャ設定
# VM作成とSSH設定

vm:
  user: k8suser
  ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCatUtquxeHqt4WQD2lJBChT6SIfZl0iHVr5kYj01GPkJNeun7/J5VQsaZEQPq4WVkYtQeVxp1eRaVawxFm0CGW5Qph6qTOSldTKp4ReYBbv4iX1m+cGPkC8KtEYTJt+sGIsnLryr11ptsoYsOob3zg6zmFwHnxJRu8BD5d8rmD+STRnKHmh8+yDmhLHryxBNdcdbPB6iwaPP+RaxWGKiZ5VlIiz8AjjUi5Mtdu6JuYVa1TgO8UygNJtC8g7r3C2GIxU9mnSBQHj26HDoRYfBkQpRpAf8OO1q0JAzXwGsn+AhEjIxEZ0hsqPaREUUATQ22oizG8DBbG+ZkBIIvo/wRJaQK3OPu94eKdg+uFx5UqbJV0vwWOXDk96CuTRq4Go8ByQdlCTlCcLj56AzDSljus0BKBq3d29vmGtNYlXrpmCVBoTR9IN/kXGTTPEXmACcTYHba/eKugDCzmdlKUi783uywcdsYhoAiLOStQD1LuzSoFfspFz69kD5m0rISWMIczzPeGS4JLH6cqWZRHheTu8cOfDj8fRTTgMZIgAMrEgLi+Jq5rtMXMw6l8+2hL4V2z/fNEMCXDRmAaVzxGrruZDUDZWlLp6vSfryyET0N2ADK+gAo05EJbnhy5BM6BwLH8yHNXJgmaq+N5lqRuY06gaBtam/5MRx+AfsMK91NPFQ== ksera@ksera-T100"

storage:
  pool_name: k8s-pool
  pool_path: /mnt/k8s-storage
  images_path: /mnt/k8s-storage/images
  
libvirt:
  network_name: k8s-network
  bridge_name: virbr0
  
terraform:
  backend: local
  state_path: ./terraform.tfstate