# プラットフォームサービス設定
# ArgoCD、Harbor、cert-manager等の設定

argocd:
  namespace: argocd
  version: v2.9.3
  repo_url: https://github.com/ksera524/k8s_myHome.git
  target_revision: main
  path: manifests
  
harbor:
  namespace: harbor
  version: v2.9.0
  admin_password: Harbor12345  # 初期パスワード（変更推奨）
  storage_class: local-path
  
cert_manager:
  namespace: cert-manager
  version: v1.13.0
  cluster_issuer: letsencrypt-staging
  
external_secrets:
  namespace: external-secrets
  backend: pulumi
  project: k8s-myhome
  environment: home
  
ingress_nginx:
  namespace: ingress-nginx
  version: 4.8.3
  
github_actions:
  namespace: arc-systems
  controller_namespace: arc-systems
  runner_namespace: arc-runners
  min_runners: 1
  max_runners: 3