apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack
  namespace: sandbox
  labels:
    app: slack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack
  template:
    metadata:
      labels:
        app: slack
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: harbor-http
      containers:
      - name: slack
        image: 192.168.122.100/sandbox/slack.rs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        workingDir: /app
        env:
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack3
              key: token
        - name: RUST_BACKTRACE
          value: "1"
        - name: RUST_LOG
          value: "slack=debug,info"
        command: ["/bin/bash", "-c"]
        args: ["echo 'Starting Slack application...' && echo 'Environment check:' && env | grep -E '(SLACK|RUST)' && echo 'Binary check:' && ls -la /app/slack && echo 'Executing binary...' && timeout 5 ./slack || echo 'Binary execution failed with exit code:' $?"]


---
apiVersion: v1
kind: Service
metadata:
  name: slack
  namespace: sandbox
spec:
  type: NodePort
  selector:
    app: slack
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32001
