apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack
  namespace: sandbox
  labels:
    app: slack
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: slack
  template:
    metadata:
      labels:
        pod: slack
    spec:
      imagePullSecrets:
        - name: harbor-http
      containers:
      - name: slack
        image: 192.168.122.100/sandbox/slack.rs:latest
        env:
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack3
              key: token


---
apiVersion: v1
kind: Service
metadata:
  name: slack
  namespace: sandbox
spec:
  type: NodePort
  selector:
    pod: slack
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32001
