apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack
  namespace: sandbox
  labels:
    app: slack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack
  template:
    metadata:
      labels:
        app: slack
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: harbor-http
      containers:
      - name: slack
        image: 192.168.122.100/sandbox/slack.rs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        workingDir: /app
        env:
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack3
              key: token
        - name: RUST_BACKTRACE
          value: "full"
        - name: RUST_LOG
          value: "debug"
        command: ["/bin/bash", "-c"]
        args: ["echo 'Starting Slack application...' && echo 'SLACK_BOT_TOKEN length:' && echo ${#SLACK_BOT_TOKEN} && echo 'Token value:' && echo $SLACK_BOT_TOKEN && echo 'Starting application...' && exec ./slack"]


---
apiVersion: v1
kind: Service
metadata:
  name: slack
  namespace: sandbox
spec:
  type: NodePort
  selector:
    app: slack
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32001
