apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-externalsecret
  namespace: sandbox
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: slack
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        webhook_url: "https://hooks.slack.com/services/DUMMY/DUMMY/DUMMY"
        bot_token: "xoxb-dummy-token"
        app_token: "xapp-dummy-token"
        channel: "#general"
        username: "bot"
        token: "xoxb-dummy-token"
  data:
  - secretKey: dummy
    remoteRef:
      key: harbor