apiVersion: batch/v1
kind: CronJob
metadata:
  name: hitomi-monitor
  namespace: sandbox
spec:
  schedule: "0 9 * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600
      backoffLimit: 0 
      template:
        metadata:
          labels:
            app: hitomi-monitor
        spec:
          containers:
            - name: hitomi-monitor
              image: 192.168.122.100/sandbox/hitomi:latest
              imagePullPolicy: Always
              env:
                - name: TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: slack3
                      key: token
                - name: DATABASE_USER
                  valueFrom:
                    secretKeyRef:
                      name: tidb
                      key: username
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: tidb
                      key: password
                - name: DATABASE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: tidb
                      key: dbname
                - name: DATABASE_HOST
                  valueFrom:
                    secretKeyRef:
                      name: tidb
                      key: host
                - name: DATABASE_PORT
                  valueFrom:
                    secretKeyRef:
                      name: tidb
                      key: port
          restartPolicy: Never
          imagePullSecrets:
            - name: harbor-http
