---
# Worker node specific tasks
- name: Install NFS client packages
  apt:
    name:
      - nfs-common
    state: present

- name: Wait for control plane to be ready
  wait_for:
    host: "{{ hostvars[groups['control_plane'][0]]['ansible_default_ipv4']['address'] }}"
    port: 6443
    timeout: 300

- name: Join worker node to cluster
  command: "{{ hostvars[groups['control_plane'][0]]['kubernetes_join_command'] }}"
  register: join_result
  changed_when: "'This node has joined the cluster' in join_result.stdout"
  failed_when: join_result.rc != 0 and 'already exists' not in join_result.stderr

- name: Display join result
  debug:
    var: join_result.stdout_lines