apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: sandbox
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: harbor-registry
      containers:
        - name: blog
          image: harbor.qroksera.com/sandbox/blog:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
# blog用Service
apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: sandbox
  labels:
    app: blog
spec:
  selector:
    app: blog
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
