# Grafana Cloud接続用のExternal Secret
# Pulumi ESCからGrafana Cloudの認証情報を取得
# 注意: Pulumi ESCの "grafana" キーには単一のAPI Keyのみが含まれている場合、
# この設定を適切に調整する必要があります
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud-credentials
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana-cloud
    app.kubernetes.io/part-of: monitoring
spec:
  # リフレッシュ間隔
  refreshInterval: 1h
  
  # Secret Store参照（既存のpulumi-esc-storeを使用）
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  
  # 作成するSecretの設定
  target:
    name: grafana-cloud-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      engineVersion: v2
      data:
        # Grafana Cloudの設定
        # Grafana Cloud Stack (ksera524) の接続情報
        GRAFANA_CLOUD_LOKI_URL: "https://logs-prod-030.grafana.net/loki/api/v1/push"
        GRAFANA_CLOUD_LOKI_USERNAME: "1328813"
        GRAFANA_CLOUD_LOKI_PASSWORD: "{{ .grafana }}"  # Pulumi ESCのgrafanaキーからAPI Keyを取得
      metadata:
        labels:
          app.kubernetes.io/name: grafana-cloud
          app.kubernetes.io/part-of: monitoring
  
  # Pulumi ESCから取得するデータ
  data:
    # GrafanaキーからAPI Keyを取得
    - secretKey: grafana
      remoteRef:
        key: grafana
---
# Promtail用のConfigMapでGrafana Cloud接続設定を管理
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-grafana-cloud-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/part-of: monitoring
data:
  # Grafana Cloud接続の設定例
  # 実際の値はExternal Secretから環境変数として注入される
  grafana-cloud-setup.md: |
    # Grafana Cloud セットアップ手順
    
    ## 1. Grafana Cloud Free Plan登録
    1. https://grafana.com/products/cloud/ にアクセス
    2. "Get started for free" をクリック
    3. アカウントを作成
    
    ## 2. Loki Data Source設定
    1. Grafana Cloudダッシュボードにログイン
    2. "Connections" → "Data sources" → "Add data source"
    3. "Loki" を選択
    4. 以下の情報を取得：
       - URL: Loki のプッシュエンドポイント
       - User: 数値のUser ID
       - Password: API Key
    
    ## 3. Pulumi ESCに認証情報を設定
    ```bash
    # Pulumi ESCプロジェクトで以下の値を設定
    pulumi config set grafana-cloud.loki-url "https://logs-prod-xxx.grafana.net/loki/api/v1/push"
    pulumi config set grafana-cloud.loki-username "123456"
    pulumi config set --secret grafana-cloud.loki-api-key "glc_xxxxxxxxxxxxx"
    ```
    
    ## 4. デプロイ確認
    ```bash
    # External Secretの同期確認
    kubectl get externalsecret grafana-cloud-credentials -n monitoring
    
    # Secretが作成されているか確認
    kubectl get secret grafana-cloud-credentials -n monitoring
    
    # Promtailのログ確認
    kubectl logs -n monitoring -l app.kubernetes.io/name=promtail
    ```
    
    ## 5. Grafana Cloudでログ確認
    1. Grafana Cloudダッシュボードにログイン
    2. "Explore" を選択
    3. Data sourceで "Loki" を選択
    4. LogQLクエリを実行：
       ```
       {namespace="argocd"}
       ```