apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud-monitoring
  namespace: monitoring
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  data:
    - secretKey: api-token
      remoteRef:
        key: grafana  # 既存の grafana キーを使用