# k8s_myHome最適化設定
installCRDs: true
replicaCount: 1

# リソース制限（ホームラボ環境）
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 32Mi

# Prometheus監視有効化
serviceMonitor:
  enabled: true
  additionalLabels:
    release: prometheus

# Webhook設定
webhook:
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 32Mi

# 証明書コントローラー設定
certController:
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 32Mi

# セキュリティ設定
securityContext:
  runAsNonRoot: true
  runAsUser: 65534

# ログレベル設定
env:
  LOG_LEVEL: info
