apiVersion: apps/v1
kind: Deployment
metadata:
  name: cooklog
  namespace: sandbox
  labels:
    app: cooklog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cooklog
  template:
    metadata:
      labels:
        app: cooklog
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: harbor-registry
      containers:
        - name: cooklog
          image: harbor.qroksera.com/sandbox/cooklog:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
# cooklog用Service（内部公開のみ）
apiVersion: v1
kind: Service
metadata:
  name: cooklog
  namespace: sandbox
  labels:
    app: cooklog
spec:
  selector:
    app: cooklog
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
