apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-init-script
  namespace: harbor
data:
  init.sh: |
    #!/bin/sh
    set -e
    
    HARBOR_URL="https://harbor.local"
    HARBOR_USER="admin"
    HARBOR_PASSWORD="Harbor12345"
    
    # Wait for Harbor to be ready
    echo "Waiting for Harbor to be ready..."
    MAX_RETRIES=30
    RETRY_COUNT=0
    
    until curl -k -f "$HARBOR_URL/api/v2.0/systeminfo" -H "Host: harbor.local" > /dev/null 2>&1; do
      if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
        echo "Harbor is not ready after $MAX_RETRIES attempts. Exiting."
        exit 1
      fi
      echo "Harbor not ready yet, waiting... (attempt $((RETRY_COUNT + 1))/$MAX_RETRIES)"
      sleep 30
      RETRY_COUNT=$((RETRY_COUNT + 1))
    done
    
    echo "Harbor is ready!"
    
    # Create CI user
    echo "Creating CI user..."
    curl -k -X POST "$HARBOR_URL/api/v2.0/users" \
      -u "$HARBOR_USER:$HARBOR_PASSWORD" \
      -H "Content-Type: application/json" \
      -H "Host: harbor.local" \
      -d '{
        "username": "ci-user",
        "email": "ci@example.com", 
        "password": "CIUser12345",
        "realname": "CI User",
        "comment": "User for CI/CD operations"
      }' && echo "CI user created successfully" || echo "CI user might already exist"
    
    # Create sandbox project
    echo "Creating sandbox project..."
    curl -k -X POST "$HARBOR_URL/api/v2.0/projects" \
      -u "$HARBOR_USER:$HARBOR_PASSWORD" \
      -H "Content-Type: application/json" \
      -H "Host: harbor.local" \
      -d '{
        "project_name": "sandbox",
        "public": false,
        "metadata": {
          "auto_scan": "true",
          "enable_content_trust": "false", 
          "prevent_vul": "false",
          "severity": "high"
        }
      }' && echo "Sandbox project created successfully" || echo "Sandbox project might already exist"
    
    # Add CI user to sandbox project with Developer role
    echo "Adding CI user to sandbox project..."
    curl -k -X POST "$HARBOR_URL/api/v2.0/projects/sandbox/members" \
      -u "$HARBOR_USER:$HARBOR_PASSWORD" \
      -H "Content-Type: application/json" \
      -H "Host: harbor.local" \
      -d '{
        "role_id": 2,
        "member_user": {
          "username": "ci-user"
        }
      }' && echo "CI user added to project successfully" || echo "CI user might already be a member"
    
    echo "Harbor initialization completed successfully!"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: harbor-init
  namespace: harbor
spec:
  template:
    spec:
      containers:
      - name: harbor-init
        image: curlimages/curl:latest
        command: ["/bin/sh", "/scripts/init.sh"]
        volumeMounts:
        - name: init-script
          mountPath: /scripts
      volumes:
      - name: init-script
        configMap:
          name: harbor-init-script
          defaultMode: 0755
      restartPolicy: OnFailure
  backoffLimit: 3