# Harbor HTTP設定用ConfigMap修正
apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-core
  namespace: harbor
  labels:
    app: harbor
    chart: harbor
    heritage: Helm
    release: harbor
data:
  EXT_ENDPOINT: "http://192.168.122.100"  # HTTPアクセス用IP設定
  TOKEN_SERVICE_URL: "http://harbor-core:80/service/token"  # Internal token service
  # 他の設定値は既存のまま保持される
---
# Harbor Registry内部設定用ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-registry
  namespace: harbor
  labels:
    app: harbor
    chart: harbor
    heritage: Helm
    release: harbor
data:
  # Registry用設定（必要に応じて）
  REGISTRY_HTTP_SECRET: "not-a-secure-secret"
  REGISTRY_REDIS_ADDR: "harbor-redis:6379"
  REGISTRY_REDIS_DB: "1"