apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # GitHub OAuth設定
  url: "https://argocd.qroksera.com"
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientId: $argocd-github-oauth:client-id
        clientSecret: $argocd-github-oauth:client-secret
        orgs:
        - name: your-github-org
        redirectURI: https://argocd.qroksera.com/api/dex/callback
