apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-oauth-secret
  namespace: argocd
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: argocd-github-oauth
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        client-id: "Ov23li8T6IFuiuLcoSJa"
        client-secret: "{{ .argocd }}"
  data:
  - secretKey: argocd
    remoteRef:
      key: argocd
