apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin-secret
  namespace: harbor
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: harbor-admin
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: harbor-admin-secret
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        username: "admin"
        password: '{{ .harbor }}'
  data:
    - secretKey: harbor
      remoteRef:
        key: harbor
