apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - harbor-admin-secret.yaml
  - harbor-registry-default.yaml
  - harbor-registry-argocd.yaml
  - harbor-registry-sandbox.yaml
