apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-secret
  namespace: cloudflared
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: cloudflared-auth
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: cloudflared
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        token: "{{ .cloudflared | default \"\" }}"
  data:
    - secretKey: cloudflared
      remoteRef:
        key: cloudflared
