all:
  children:
    k8s_cluster:
      children:
        control_plane:
          hosts:
            k8s-control-plane-1:
              ansible_host: "{{ hostvars['localhost']['control_plane_ip'] | default('192.168.122.10') }}"
              kubernetes_role: master
        workers:
          hosts:
            k8s-worker-1:
              ansible_host: "{{ hostvars['localhost']['worker_1_ip'] | default('192.168.122.11') }}"
              kubernetes_role: worker
            k8s-worker-2:
              ansible_host: "{{ hostvars['localhost']['worker_2_ip'] | default('192.168.122.12') }}"
              kubernetes_role: worker
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        
        # Kubernetes cluster configuration
        kubernetes_version: "1.28.0"
        pod_network_cidr: "10.244.0.0/16"
        service_subnet: "10.96.0.0/12"
        
        # Docker configuration
        docker_version: "5:24.0.5-1~ubuntu.22.04~jammy"
        
        # External storage
        external_storage_path: "/mnt/external-ssd"