apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-admin-secret
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: pulumi-esc-store
    kind: SecretStore
  target:
    name: harbor-admin-secret
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        # Harbor Core用パスワード
        HARBOR_ADMIN_PASSWORD: "{{ .adminPassword }}"
        # CI/CD用パスワード  
        HARBOR_CI_PASSWORD: "{{ .ciPassword }}"
        # Docker Registry認証用
        .dockerconfigjson: |
          {
            "auths": {
              "192.168.122.100": {
                "username": "admin",
                "password": "{{ .adminPassword }}",
                "auth": "{{ printf "admin:%s" .adminPassword | b64enc }}"
              }
            }
          }
  data:
  - secretKey: adminPassword
    remoteRef:
      key: harbor.admin_password
  - secretKey: ciPassword
    remoteRef:
      key: harbor.ci_password

---
# Harbor CI用Secretも同時作成
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-ci-secret
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: pulumi-esc-store
    kind: SecretStore
  target:
    name: harbor-ci-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "192.168.122.100": {
                "username": "ciuser",
                "password": "{{ .ciPassword }}",
                "auth": "{{ printf "ciuser:%s" .ciPassword | b64enc }}"
              }
            }
          }
  data:
  - secretKey: ciPassword
    remoteRef:
      key: harbor.ci_password