apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin-secret
  namespace: harbor
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: harbor-admin-secret
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        # Harbor Core用パスワード（automation用）
        username: "admin"
        password: "{{ .admin_password | default \"Harbor12345\" }}"
        # CI/CD用パスワード  
        HARBOR_CI_PASSWORD: "{{ .ci_password | default \"Harbor12345\" }}"
        # Docker Registry認証用
        .dockerconfigjson: |
          {
            "auths": {
              "192.168.122.100": {
                "username": "admin",
                "password": "{{ .admin_password | default \"Harbor12345\" }}",
                "auth": "{{ printf "admin:%s" (.admin_password | default \"Harbor12345\") | b64enc }}"
              }
            }
          }
  data:
  - secretKey: harbor-config
    remoteRef:
      key: harbor

---
# Harbor CI用Secretも同時作成
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-ci-secret
  namespace: harbor
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: harbor-ci-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "192.168.122.100": {
                "username": "ciuser",
                "password": "Harbor12345",
                "auth": "{{ printf "ciuser:Harbor12345" | b64enc }}"
              }
            }
          }
  data:
  - secretKey: harbor-config
    remoteRef:
      key: harbor