apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack
  namespace: sandbox
  labels:
    app: slack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack
  template:
    metadata:
      labels:
        app: slack
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: harbor-http
      containers:
      - name: slack
        image: harbor.k8s.local/sandbox/slack.rs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        workingDir: /app
        env:
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack
              key: SLACK_BOT_TOKEN
        - name: RUST_LOG
          value: "INFO"
        command: ["./slack"]
        # GitHub Actionsでビルドしたイメージの即時終了対策
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "test -f /app/slack"
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3


---
apiVersion: v1
kind: Service
metadata:
  name: slack
  namespace: sandbox
spec:
  type: NodePort
  selector:
    app: slack
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32001
