apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-ssd-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: factorio-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-ssd-storage
  local:
    path: /mnt/external-ssd/factorio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-ssd-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: factorio
  name: factorio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factorio
  template:
    metadata:
      labels:
        app: factorio
    spec:
      securityContext:
        fsGroup: 845
        runAsUser: 845
        runAsGroup: 845
      containers:
        - name: factorio-container
          image: factoriotools/factorio:stable-2.0.28
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          env:
            - name: GENERATE_NEW_SAVE
              value: 'false'
            - name: LOAD_LATEST_SAVE
              value: 'true'
            - name: DLC_SPACE_AGE
              value: 'false'
            - name: SAVE_NAME
              value: "replaceme"
          ports:
            - containerPort: 34197
              protocol: UDP
              name: "game"
            - containerPort: 27015
              protocol: TCP
              name: "rcon"
          volumeMounts:
            - mountPath: "/factorio"
              name: factorio-storage
      volumes:
        - name: factorio-storage
          persistentVolumeClaim:
            claimName: factorio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: factorio
  labels:
    app: factorio
spec:
  type: NodePort
  ports:
    - port: 34197        
      nodePort: 32000
      targetPort: game
      protocol: UDP
      name: game
    - port: 27015
      nodePort: 27015
      targetPort: rcon
      protocol: TCP
      name: rcon
  selector:
    app: factorio