apiVersion: v1
kind: PersistentVolume
metadata:
  name: external-ssd-pv-factorio-large
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/external-ssd/factorio-large

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-external-ssd-pvc-3
  namespace: factorio
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-pvc
  namespace: factorio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: factorio
  name: factorio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factorio
  template:
    metadata:
      labels:
        app: factorio
    spec:
      containers:
        - name: factorio-container
          image: factoriotools/factorio:stable
          env:
            - name: UPDATE_MODS_ON_START
              value: 'true'
          ports:
            - containerPort: 34197
              protocol: UDP
              name: "factorio-port"
          volumeMounts:
            - mountPath: "/factorio"
              name: factorio-storage
      volumes:
        - name: factorio-storage
          persistentVolumeClaim:
            claimName: factorio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: factorio-udp-service
  namespace: factorio
spec:
  type: NodePort
  selector:
    app: factorio
  ports:
    - protocol: UDP
      port: 34197
      targetPort: 34197
      nodePort: 30097
