apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-auth
  namespace: sandbox
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: rustfs-auth
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: rustfs-auth
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
  data:
    - secretKey: RUSTFS_ACCESS_KEY
      remoteRef:
        key: rustfs.access_key
    - secretKey: RUSTFS_SECRET_KEY
      remoteRef:
        key: rustfs.secret_key
