apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-secret
  namespace: sandbox
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: slack-auth
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: slack
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        SLACK_BOT_TOKEN: "{{ .slack | default \"\" }}"
        token: "{{ .slack | default \"\" }}"
  data:
    - secretKey: slack
      remoteRef:
        key: slack
