# External Secrets for GitHub Actions Runner Controller
# ESO統合によるGitHub PAT及びHarbor認証情報管理

---
# GitHub認証情報用ExternalSecret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-auth-secret
  namespace: arc-systems
spec:
  refreshInterval: 20s
  secretStoreRef:
    kind: ClusterSecretStore
    name: pulumi-esc-store
  target:
    name: github-auth
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        github_token: "{{ .github_token }}"
        username: "{{ .github_username }}"
  data:
  - secretKey: github_token
    remoteRef:
      key: github
      property: token
  - secretKey: github_username
    remoteRef:
      key: github
      property: username

---
# GitHub Token用ExternalSecret (shared-secret用)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token-secret
  namespace: arc-systems
spec:
  refreshInterval: 20s
  secretStoreRef:
    kind: ClusterSecretStore
    name: pulumi-esc-store
  target:
    name: github-token
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        github_token: "{{ .github }}"
  data:
  - secretKey: github
    remoteRef:
      key: github

---
# Harbor認証情報用ExternalSecret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-auth-secret
  namespace: arc-systems
spec:
  refreshInterval: 20s
  secretStoreRef:
    kind: ClusterSecretStore
    name: pulumi-esc-store
  target:
    name: harbor-auth
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        HARBOR_URL: "{{ .harbor_url }}"
        HARBOR_USERNAME: "{{ .harbor_username }}"
        HARBOR_PASSWORD: "{{ .harbor_password }}"
        HARBOR_PROJECT: "{{ .harbor_project }}"
  data:
  - secretKey: harbor_url
    remoteRef:
      key: harbor
      property: url
  - secretKey: harbor_username
    remoteRef:
      key: harbor
      property: username
  - secretKey: harbor_password
    remoteRef:
      key: harbor
      property: password
  - secretKey: harbor_project
    remoteRef:
      key: harbor
      property: project

---
# Harbor Registry Secret (Docker config format)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-registry-secret
  namespace: arc-systems
spec:
  refreshInterval: 20s
  secretStoreRef:
    kind: ClusterSecretStore
    name: pulumi-esc-store
  target:
    name: harbor-registry-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .harbor_url }}": {
                "username": "{{ .harbor_username }}",
                "password": "{{ .harbor_password }}",
                "auth": "{{ printf "%s:%s" .harbor_username .harbor_password | b64enc }}"
              }
            }
          }
  data:
  - secretKey: harbor_url
    remoteRef:
      key: harbor
      property: url
  - secretKey: harbor_username
    remoteRef:
      key: harbor
      property: username
  - secretKey: harbor_password
    remoteRef:
      key: harbor
      property: password