apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared
  name: cloudflared
  namespace: cloudflared
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - cloudflared
              topologyKey: kubernetes.io/hostname
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:2026.1.2
        imagePullPolicy: IfNotPresent
        command:
        - cloudflared
        - tunnel
        - --config
        - /etc/cloudflared/config.yml
        - --metrics
        - 0.0.0.0:2000
        - --no-autoupdate
        - run
        volumeMounts:
        - name: cloudflared-config
          mountPath: /etc/cloudflared
        - name: cloudflared-credentials
          mountPath: /etc/cloudflared/creds
          readOnly: true
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 5
          initialDelaySeconds: 20
          timeoutSeconds: 10
          periodSeconds: 15
        startupProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 30
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 5
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 10
      volumes:
      - name: cloudflared-config
        configMap:
          name: cloudflared-config
      - name: cloudflared-credentials
        secret:
          secretName: cloudflared
          items:
          - key: token
            path: credentials.json
