# Harbor Docker Registry Secrets for multiple namespaces
# Pulumiから取得したHarbor認証情報を各namespaceに作成
---
# Default namespace用
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-http-secret
  namespace: default
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: harbor-registry
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: harbor-http
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "192.168.122.100": {
                "username": "admin",
                "password": "{{ .harbor }}",
                "auth": "{{ printf "admin:%s" .harbor | b64enc }}"
              }
            }
          }
  data:
  - secretKey: harbor
    remoteRef:
      key: harbor
---
# Sandbox namespace用
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-http-secret
  namespace: sandbox
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: harbor-registry
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: harbor-http
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "192.168.122.100": {
                "username": "admin",
                "password": "{{ .harbor }}",
                "auth": "{{ printf "admin:%s" .harbor | b64enc }}"
              }
            }
          }
  data:
  - secretKey: harbor
    remoteRef:
      key: harbor
---
# Production namespace用
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-http-secret
  namespace: production
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: harbor-registry
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: harbor-http
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "192.168.122.100": {
                "username": "admin",
                "password": "{{ .harbor }}",
                "auth": "{{ printf "admin:%s" .harbor | b64enc }}"
              }
            }
          }
  data:
  - secretKey: harbor
    remoteRef:
      key: harbor
---
# Staging namespace用
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-http-secret
  namespace: staging
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: harbor-registry
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: harbor-http
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "192.168.122.100": {
                "username": "admin",
                "password": "{{ .harbor }}",
                "auth": "{{ printf "admin:%s" .harbor | b64enc }}"
              }
            }
          }
  data:
  - secretKey: harbor
    remoteRef:
      key: harbor