apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: pulumi-esc-store
  namespace: external-secrets-system
spec:
  provider:
    pulumi:
      organization: "ksera524"
      project: "k8s-myhome"  
      environment: "production"
      accessToken:
        secretRef:
          name: pulumi-esc-auth
          key: access-token

---
# Harbor namespace用SecretStore
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: pulumi-esc-store
  namespace: harbor
spec:
  provider:
    pulumi:
      organization: "ksera524"
      project: "k8s-myhome"  
      environment: "production"
      accessToken:
        secretRef:
          name: pulumi-esc-auth
          key: access-token
          
---
# Actions Runner System namespace用SecretStore
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: pulumi-esc-store
  namespace: actions-runner-system
spec:
  provider:
    pulumi:
      organization: "ksera524"
      project: "k8s-myhome"  
      environment: "production"
      accessToken:
        secretRef:
          name: pulumi-esc-auth
          key: access-token