# External Secret が直接 argocd-secret を管理（make all対応）
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-oauth-secret
  namespace: argocd
spec:
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge  # 既存のSecretとマージ
  data:
  - secretKey: dex.github.clientSecret
    remoteRef:
      key: argocd
      property: client-secret
  - secretKey: dex.github.clientId
    remoteRef:
      key: github
      property: client-id
  refreshInterval: 15m  # より頻繁な同期でmake all後の確実性向上