apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-multi-repo-secret
  namespace: arc-systems
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: github-actions-token
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: github-multi-repo-secret
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        github_token: "{{ .github }}"
  data:
    - secretKey: github
      remoteRef:
        key: github
