# External Secret が直接 argocd-secret を管理
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-oauth-secret
  namespace: argocd
spec:
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    type: Opaque
    creationPolicy: Merge  # 既存のSecretとマージ
  data:
  - secretKey: dex.github.clientSecret
    remoteRef:
      key: argocd
      property: client-secret