apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-oauth-secret
  namespace: argocd
spec:
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: argocd-github-oauth
    type: Opaque
  data:
  - secretKey: client-id
    remoteRef:
      key: argocd
      property: client-id
  - secretKey: client-secret
    remoteRef:
      key: argocd
      property: client-secret
---
# ArgoCD Secretに直接GitHub OAuth情報を追加するパッチ
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
stringData:
  # GitHub OAuth設定（Base64エンコード前の値）
  # External Secretから値を取得してこのSecretにコピーする必要があります
  # この部分は外部プロセスで更新される
  dex.github.clientId: "Ov23li8T6IFuiuLcoSJa"
  # dex.github.clientSecret は External Secret から取得