apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.external-secrets.io'
    targetRevision: '0.18.2'
    chart: external-secrets
    helm:
      values: |
        installCRDs: true
        replicaCount: 1
        
        # リソース制限（k8s_myHome環境最適化）
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 32Mi
        
        # Prometheus監視有効化
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: prometheus
        
        # Webhook設定
        webhook:
          replicaCount: 1
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 32Mi
        
        # 証明書コントローラー設定
        certController:
          replicaCount: 1
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 32Mi
        
        # セキュリティ設定
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
        
        # ログレベル設定
        env:
          LOG_LEVEL: info
          
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets-system
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      
  # CRD更新時の差分無視
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jqPathExpressions:
    - '.spec.conversion.webhook.clientConfig.caBundle'