# Harbor用ExternalSecret設定
# Pulumi ESCからHarbor認証情報を自動取得
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin-secret
  namespace: harbor
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: harbor-auth
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: harbor-admin-secret
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        # Harbor Core用パスワード（automation用）
        username: "admin"
        password: "{{ .harbor | default \"Harbor12345\" }}"
        # CI/CD用パスワード  
        HARBOR_CI_PASSWORD: "{{ .harbor_ci | default \"Harbor12345\" }}"
        # Docker Registry認証用
        .dockerconfigjson: |
          {
            "auths": {
              "192.168.122.100": {
                "username": "admin",
                "password": "{{ .harbor | default \"Harbor12345\" }}",
                "auth": "{{ printf \"admin:%s\" (.harbor | default \"Harbor12345\") | b64enc }}"
              }
            }
          }
  data:
  - secretKey: harbor
    remoteRef:
      key: harbor
  - secretKey: harbor_ci
    remoteRef:
      key: harbor_ci

---
# Harbor CI用ExternalSecret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-ci-secret
  namespace: harbor
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: harbor-ci-auth
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: harbor-ci-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "192.168.122.100": {
                "username": "ciuser",
                "password": "{{ .harbor_ci | default \"Harbor12345\" }}",
                "auth": "{{ printf \"ciuser:%s\" (.harbor_ci | default \"Harbor12345\") | b64enc }}"
              }
            }
          }
  data:
  - secretKey: harbor_ci
    remoteRef:
      key: harbor_ci

---
# GitHub Actions用Harbor認証Secret (arc-systems namespace)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-auth-secret
  namespace: arc-systems
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: github-actions-auth
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: harbor-auth
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        HARBOR_USERNAME: "admin"
        HARBOR_PASSWORD: "{{ .harbor | default \"Harbor12345\" }}"
        HARBOR_URL: "192.168.122.100"
        HARBOR_PROJECT: "sandbox"
  data:
  - secretKey: harbor
    remoteRef:
      key: harbor
---
# Cloudflared用ExternalSecret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-secret
  namespace: cloudflared
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: cloudflared-auth
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: cloudflared
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        token: "{{ .cloudflared | default \"\" }}"
  data:
  - secretKey: cloudflared
    remoteRef:
      key: cloudflared
