apiVersion: batch/v1
kind: CronJob
metadata:
  name: rss-monitor-cronjob
  namespace: sandbox
spec:
  schedule: "0 */6 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: rss-monitor
        spec:
          containers:
            - name: rss-monitor
              image: https://192.168.10.11/sandbox/rss:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: slack
                      key: token
                - name: CHANNEL
                  value: rss
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: tidb
                      key: uri
          imagePullSecrets:
            - name: harbor
          restartPolicy: OnFailure  
``successfulJobsHistoryLimit: 3
