apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-externalsecret
  namespace: cloudflared
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: cloudflared
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: cloudflared