apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-externalsecret
  namespace: sandbox
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: slack
    creationPolicy: Owner
  data:
  - secretKey: SLACK_BOT_TOKEN
    remoteRef:
      key: slack