apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack3-externalsecret
  namespace: sandbox
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: slack3
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: slack