apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - networkpolicies.yaml
  - storage-classes/local-storage-class.yaml
  - storage-classes/local-ssd-storage-class.yaml
