# Cloudflared用ExternalSecret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-secret
  namespace: cloudflared
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: cloudflared-auth
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: cloudflared
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        token: "{{ .cloudflared | default \"\" }}"
  data:
  - secretKey: cloudflared
    remoteRef:
      key: cloudflared

---
# Slack用ExternalSecret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-bot-token
  namespace: sandbox
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: slack-auth
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: slack-bot-token
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        token: "{{ .slack_bot_token | default \"\" }}"
  data:
  - secretKey: slack_bot_token
    remoteRef:
      key: slack_bot_token