apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # GitHub OAuth設定
  # Secret参照: $dex.github.clientSecret（短縮形式で動作確認済み）
  # ESO経由でargocd.client-secretから取得
  url: "https://argocd.qroksera.com"
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientId: Ov23li8T6IFuiuLcoSJa
        clientSecret: $dex.github.clientSecret
        redirectURI: https://argocd.qroksera.com/api/dex/callback