#cloud-config
# 簡素化されたcloud-init設定

hostname: ${vm_hostname}
manage_etc_hosts: true

# ユーザー設定
users:
  - name: ${username}
    groups: [adm, cdrom, dip, plugdev, lxd, sudo]
    lock_passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_key}

# システム更新とパッケージインストール
package_update: true
package_upgrade: false  # 時間短縮のため無効

packages:
  - curl
  - wget
  - git
  - vim
  - net-tools
  - nfs-common

# 基本設定のみ
runcmd:
  # swap無効化
  - swapoff -a
  - sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
  
  # NFS共有のマウント
  - mkdir -p /mnt/nfs-storage
  - echo "192.168.122.1:/mnt/k8s-storage/nfs-share /mnt/nfs-storage nfs defaults 0 0" >> /etc/fstab
  - mount -a || true
  
  # 完了マーカー
  - touch /var/log/cloud-init-complete

# タイムゾーン設定
timezone: Asia/Tokyo

# 最小限のログ出力
final_message: "VM setup complete after $UPTIME seconds"