apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: docker-build-and-push
spec:
  ttlStrategy:
    secondsAfterCompletion: 1
    secondsAfterSuccess: 1
    secondsAfterFailure: 1
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: message
      container:
        image: docker:20.10.7
        command: [sh, -c]
        args:
          - |
            apk add --no-cache git && \
            git clone https://ksera524:$GITHUB_TOKEN@github.com/ksera524/{{inputs.parameters.message}}.git /src && \
            docker build -t 192.168.10.11:30003/sandbox/{{inputs.parameters.message}}:latest -f /src/Dockerfile /src && \
            echo $PASSWORD | docker login https://192.168.10.11:30003 -u $USER --password-stdin && \
            docker push 192.168.10.11:30003/sandbox/{{inputs.parameters.message}}:latest
        volumeMounts:
          - name: workdir
            mountPath: /src
          - name: docker-sock
            mountPath: /var/run/docker.sock
        env:
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: git-secret
                key: GITHUB_TOKEN
          - name: USER
            valueFrom:
              secretKeyRef:
                name: harbor
                key: USER
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: harbor
                key: PASSWORD

  volumes:
    - name: workdir
      emptyDir: {}
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
