apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin-secret
  namespace: harbor
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: harbor-admin-secret
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        # Harbor Core用パスワード（ESO必須）
        username: "admin"
        password: "{{ .harbor }}"
        # CI/CD用パスワード  
        HARBOR_CI_PASSWORD: "{{ .harbor }}"
        # Docker Registry認証用
        .dockerconfigjson: |
          {
            "auths": {
              "192.168.122.100": {
                "username": "admin",
                "password": "{{ .harbor }}",
                "auth": "{{ printf "admin:%s" .harbor | b64enc }}"
              }
            }
          }
  data:
  - secretKey: harbor
    remoteRef:
      key: harbor

---
# Harbor CI用Secretも同時作成
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-ci-secret
  namespace: harbor
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: harbor-ci-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "192.168.122.100": {
                "username": "ciuser",
                "password": "{{ .harbor }}",
                "auth": "{{ printf "ciuser:%s" .harbor | b64enc }}"
              }
            }
          }
  data:
  - secretKey: harbor
    remoteRef:
      key: harbor