# Harbor Registry Secret for ARC Systems namespace
# automation/platform/create-harbor-secrets.sh の代替実装
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registry-secret
  namespace: arc-systems
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: harbor-registry-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "192.168.122.100": {
                "username": "admin",
                "password": "{{ .admin_password }}",
                "auth": "{{ printf "admin:%s" .admin_password | b64enc }}"
              }
            }
          }
  data:
  - secretKey: harbor-config
    remoteRef:
      key: harbor

---
# Harbor HTTP Secret for default namespace
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-http-secret
  namespace: default
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: harbor-http
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "192.168.122.100": {
                "username": "admin",
                "password": "{{ .admin_password }}",
                "auth": "{{ printf "admin:%s" .adminPassword | b64enc }}"
              }
            }
          }
  data:
  - secretKey: harbor-config
    remoteRef:
      key: harbor

---
# Harbor HTTP Secret for sandbox namespace
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-http-secret-sandbox
  namespace: sandbox
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: harbor-http
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "192.168.122.100": {
                "username": "admin",
                "password": "{{ .admin_password }}",
                "auth": "{{ printf "admin:%s" .adminPassword | b64enc }}"
              }
            }
          }
  data:
  - secretKey: harbor-config
    remoteRef:
      key: harbor

---
# Harbor HTTP Secret for production namespace
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-http-secret-production
  namespace: production
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: harbor-http
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "192.168.122.100": {
                "username": "admin",
                "password": "{{ .admin_password }}",
                "auth": "{{ printf "admin:%s" .adminPassword | b64enc }}"
              }
            }
          }
  data:
  - secretKey: harbor-config
    remoteRef:
      key: harbor

---
# Harbor HTTP Secret for staging namespace
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-http-secret-staging
  namespace: staging
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: harbor-http
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "192.168.122.100": {
                "username": "admin",
                "password": "{{ .admin_password }}",
                "auth": "{{ printf "admin:%s" .adminPassword | b64enc }}"
              }
            }
          }
  data:
  - secretKey: harbor-config
    remoteRef:
      key: harbor