apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: pulumi-esc-store
spec:
  provider:
    pulumi:
      organization: ${PULUMI_ORG:-ksera}
      project: ${PULUMI_PROJECT:-k8s}
      environment: ${PULUMI_ENVIRONMENT:-secret}
      accessToken:
        secretRef:
          name: pulumi-access-token
          key: PULUMI_ACCESS_TOKEN
          namespace: external-secrets-system