apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-externalsecret
  namespace: sandbox
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: slack
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        # Slack API関連の認証情報
        webhook_url: "{{ .webhook_url | default \"\" }}"
        bot_token: "{{ .bot_token | default \"\" }}"
        app_token: "{{ .app_token | default \"\" }}"
        # 追加のSlack設定値
        channel: "{{ .channel | default \"#general\" }}"
        username: "{{ .username | default \"bot\" }}"
  data:
  - secretKey: slack
    remoteRef:
      key: slack
