# 簡単なHarbor接続テスト
name: Harbor Connection Test

on:
  push:
    branches: [ main ]

jobs:
  harbor-test:
    runs-on: slack.rs-runners
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Harbor認証情報取得
      run: |
        echo "=== Harbor認証情報取得 ==="
        export KUBECONFIG=/tmp/kubeconfig
        kubectl config set-cluster default \
            --server=https://kubernetes.default.svc \
            --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
            --kubeconfig=$KUBECONFIG
        kubectl config set-credentials default \
            --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) \
            --kubeconfig=$KUBECONFIG
        kubectl config set-context default \
            --cluster=default --user=default \
            --kubeconfig=$KUBECONFIG
        kubectl config use-context default --kubeconfig=$KUBECONFIG
        
        # Harbor認証情報取得
        HARBOR_USERNAME=$(kubectl get secret harbor-auth -n arc-systems -o jsonpath='{.data.HARBOR_USERNAME}' | base64 -d)
        HARBOR_PASSWORD=$(kubectl get secret harbor-auth -n arc-systems -o jsonpath='{.data.HARBOR_PASSWORD}' | base64 -d)  
        HARBOR_URL=$(kubectl get secret harbor-auth -n arc-systems -o jsonpath='{.data.HARBOR_URL}' | base64 -d)
        HARBOR_PROJECT=$(kubectl get secret harbor-auth -n arc-systems -o jsonpath='{.data.HARBOR_PROJECT}' | base64 -d)
        
        echo "Harbor URL: $HARBOR_URL"
        echo "Harbor Project: $HARBOR_PROJECT"
        
        # Harbor API接続テスト
        echo "Harbor API接続テスト中..."
        curl -u $HARBOR_USERNAME:$HARBOR_PASSWORD "http://$HARBOR_URL/api/v2.0/projects" || echo "API接続失敗"
        
        # Docker環境変数でTLS無効化
        export DOCKER_TLS_VERIFY=""
        export DOCKER_CONTENT_TRUST=0
        export DOCKER_INSECURE_REGISTRY="$HARBOR_URL"
        
        # hello-worldイメージでテスト
        echo "hello-worldイメージでpushテスト..."
        docker pull hello-world
        docker tag hello-world $HARBOR_URL/$HARBOR_PROJECT/slack.rs:test
        timeout 60 docker push $HARBOR_URL/$HARBOR_PROJECT/slack.rs:test || echo "Push失敗"
        
        echo "✅ テスト完了"