# Harbor Push デバッグ用ワークフロー
name: Harbor Push Debug

on:
  push:
    branches: [ main ]

jobs:
  harbor-debug:
    runs-on: slack.rs-runners
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Harbor認証とDocker設定
      run: |
        echo "=== Harbor認証設定 ==="
        export KUBECONFIG=/tmp/kubeconfig
        kubectl config set-cluster default \
            --server=https://kubernetes.default.svc \
            --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
            --kubeconfig=$KUBECONFIG
        kubectl config set-credentials default \
            --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) \
            --kubeconfig=$KUBECONFIG
        kubectl config set-context default \
            --cluster=default --user=default \
            --kubeconfig=$KUBECONFIG
        kubectl config use-context default --kubeconfig=$KUBECONFIG
        
        HARBOR_USERNAME=$(kubectl get secret harbor-auth -n arc-systems -o jsonpath='{.data.HARBOR_USERNAME}' | base64 -d)
        HARBOR_PASSWORD=$(kubectl get secret harbor-auth -n arc-systems -o jsonpath='{.data.HARBOR_PASSWORD}' | base64 -d)  
        HARBOR_URL=$(kubectl get secret harbor-auth -n arc-systems -o jsonpath='{.data.HARBOR_URL}' | base64 -d)
        HARBOR_PROJECT=$(kubectl get secret harbor-auth -n arc-systems -o jsonpath='{.data.HARBOR_PROJECT}' | base64 -d)
        
        echo "Harbor URL: $HARBOR_URL"
        echo "Harbor Project: $HARBOR_PROJECT"
        
        # Docker環境変数設定
        export DOCKER_TLS_VERIFY=""
        export DOCKER_CONTENT_TRUST=0
        export DOCKER_INSECURE_REGISTRY="$HARBOR_URL"
        
        # Docker daemon設定確認
        echo "=== Docker daemon設定確認 ==="
        docker version || echo "Docker version確認失敗"
        docker info | grep -A5 -B5 "Insecure Registries" || echo "Insecure Registries設定なし"
        
        # Docker login テスト（詳細エラー表示）
        echo "=== Docker login テスト ==="
        echo "$HARBOR_PASSWORD" | docker login $HARBOR_URL -u "$HARBOR_USERNAME" --password-stdin || echo "Docker login失敗"
        
        # Hello-worldでテスト
        echo "=== イメージpullとtag ==="
        docker pull hello-world
        docker tag hello-world $HARBOR_URL/$HARBOR_PROJECT/slack.rs:debug-test
        
        echo "=== Dockerイメージ一覧 ==="
        docker images | grep $HARBOR_URL || echo "タグ付けされたイメージなし"
        
        # Push試行（詳細ログ付き）
        echo "=== Docker push 詳細デバッグ ==="
        docker push $HARBOR_URL/$HARBOR_PROJECT/slack.rs:debug-test -v 2>&1 || echo "Push失敗"
        
        echo "=== 完了 ==="