#!/bin/bash

# GitHub Actions Runner Controller (ARC) - 新しいリポジトリ用Runner追加スクリプト
# 公式GitHub ARC対応版 - クリーンで簡潔な実装

set -euo pipefail

# 共通ライブラリを読み込み
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
source "$SCRIPTS_ROOT/common-k8s-utils.sh"
source "$SCRIPTS_ROOT/common-logging.sh"

# 引数確認
if [[ $# -lt 1 ]]; then
    log_error "使用方法: $0 <repository-name> [min-runners] [max-runners]"
    log_error "例: $0 my-awesome-project 1 3"
    exit 1
fi

REPOSITORY_NAME="$1"
# デフォルト値を設定（引数が渡されない場合）
MIN_RUNNERS="${2:-1}"
MAX_RUNNERS="${3:-3}"
# Runner名生成（小文字変換、ドット・アンダースコアをハイフンに変換）
RUNNER_NAME="$(echo "${REPOSITORY_NAME}" | tr '[:upper:]._' '[:lower:]--')-runners"

log_status "=== GitHub Actions Runner追加スクリプト (公式ARC対応) ==="
log_debug "対象リポジトリ: $REPOSITORY_NAME"
log_debug "Runner名: $RUNNER_NAME"
log_debug "Min Runners: $MIN_RUNNERS"
log_debug "Max Runners: $MAX_RUNNERS"

# GitHubユーザー名を取得（settings.tomlから）
# settings.tomlはautomation直下にある
SETTINGS_FILE="$SCRIPTS_ROOT/../settings.toml"
if [[ ! -f "$SETTINGS_FILE" ]]; then
    # 別の場所も試す（プロジェクトルートから実行される場合）
    SETTINGS_FILE="$SCRIPTS_ROOT/../../settings.toml"
    if [[ ! -f "$SETTINGS_FILE" ]]; then
        # platform-deploy.shから呼ばれる場合
        SETTINGS_FILE="$(dirname "$SCRIPTS_ROOT")/settings.toml"
        if [[ ! -f "$SETTINGS_FILE" ]]; then
            log_error "settings.tomlが見つかりません"
            log_error "automation/settings.tomlを作成してください"
            exit 1
        fi
    fi
fi

log_debug "settings.tomlファイル: $SETTINGS_FILE"
GITHUB_USERNAME=$(grep '^username = ' "$SETTINGS_FILE" | head -1 | cut -d'"' -f2)
if [[ -z "$GITHUB_USERNAME" ]]; then
    log_error "settings.tomlのgithub.usernameが設定されていません"
    log_error "ファイル: $SETTINGS_FILE"
    exit 1
fi
log_debug "GitHub Username: $GITHUB_USERNAME"

PROJECT_ROOT="$(cd "$SCRIPTS_ROOT/../.." && pwd)"
APPSET_FILE="$PROJECT_ROOT/manifests/platform/ci-cd/github-actions/runners-appset.yaml"

if [[ ! -f "$APPSET_FILE" ]]; then
    log_error "ApplicationSet定義が見つかりません: $APPSET_FILE"
    exit 1
fi

log_status "=== Runner定義をGitOps管理へ登録 ==="
UPSERT_RESULT=$(python3 - <<PY
import re
import sys
from pathlib import Path
import yaml

appset_path = Path(r"$APPSET_FILE")
repo_name = r"$REPOSITORY_NAME"
min_runners = str(r"$MIN_RUNNERS")
max_runners = str(r"$MAX_RUNNERS")
github_owner = r"$GITHUB_USERNAME"

doc = yaml.safe_load(appset_path.read_text(encoding="utf-8"))
elements = doc["spec"]["generators"][0]["list"]["elements"]

slug = re.sub(r"[._]", "-", repo_name.lower())
entry = {
    "name": slug,
    "githubOwner": github_owner,
    "githubRepo": repo_name,
    "runnerName": f"{slug}-runners",
    "minRunners": min_runners,
    "maxRunners": max_runners,
}

updated = False
for i, e in enumerate(elements):
    if e.get("runnerName") == entry["runnerName"] or e.get("githubRepo") == repo_name:
        if e != entry:
            elements[i] = entry
            updated = True
        print("updated" if updated else "unchanged")
        break
else:
    elements.append(entry)
    updated = True
    print("added")

if updated:
    appset_path.write_text(yaml.safe_dump(doc, sort_keys=False, allow_unicode=False), encoding="utf-8")
PY
)

case "$UPSERT_RESULT" in
    added)
        log_status "✓ Runner定義を追加しました: $REPOSITORY_NAME"
        ;;
    updated)
        log_status "✓ Runner定義を更新しました: $REPOSITORY_NAME"
        ;;
    unchanged)
        log_status "✓ Runner定義は最新です: $REPOSITORY_NAME"
        ;;
    *)
        log_error "Runner定義の更新に失敗しました"
        exit 1
        ;;
esac

log_status "ℹ️ Runner本体はArgoCD(ApplicationSet)経由でデプロイされます"
log_status "ℹ️ 反映にはこのリポジトリのcommit/pushが必要です"

# GitHub Actions workflow作成
log_status "=== GitHub Actions workflow作成 ==="

WORKFLOW_DIR=".github/workflows"
WORKFLOW_FILE="$WORKFLOW_DIR/build-and-push-$REPOSITORY_NAME.yml"

# .github/workflowsディレクトリ作成
mkdir -p "$WORKFLOW_DIR"
log_debug "Workflowディレクトリ作成: $WORKFLOW_DIR"

# workflow.yamlファイル作成
log_debug "Workflowファイル作成中: $WORKFLOW_FILE"
cat > "$WORKFLOW_FILE" << WORKFLOW_EOF
# GitHub Actions workflow for $REPOSITORY_NAME
# Auto-generated by add-runner.sh (公式ARC対応版) - Build/Pull分離版

name: Build and Push to Harbor - $REPOSITORY_NAME

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pull-requests: read

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        echo "=== Build image on GitHub-hosted runner ==="
        docker build -t $REPOSITORY_NAME:ci .

    - name: Export Docker image tar
      run: |
        docker save $REPOSITORY_NAME:ci | gzip > /tmp/$REPOSITORY_NAME-image.tar.gz

    - name: Upload image artifact
      uses: actions/upload-artifact@v4
      with:
        name: $REPOSITORY_NAME-image
        path: /tmp/$REPOSITORY_NAME-image.tar.gz
        retention-days: 1

  push-image:
    if: github.event_name == 'push'
    needs: build-image
    runs-on: $RUNNER_NAME

    steps:
    - name: Download image artifact
      uses: actions/download-artifact@v4
      with:
        name: $REPOSITORY_NAME-image
        path: /tmp

    - name: Load Docker image
      run: |
        echo "=== Load image on self-hosted runner ==="
        gunzip -c /tmp/$REPOSITORY_NAME-image.tar.gz | docker load

    - name: Setup kubectl and Harbor credentials
      run: |
        echo "=== Setup kubectl and Harbor credentials ==="
        
        # Install kubectl
        echo "Installing kubectl..."
        curl -LO "https://dl.k8s.io/release/\$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        
        # Configure kubectl for in-cluster access
        echo "Configuring kubectl..."
        export KUBECONFIG=/tmp/kubeconfig
        kubectl config set-cluster default \\
            --server=https://kubernetes.default.svc \\
            --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt \\
            --kubeconfig=\$KUBECONFIG
        kubectl config set-credentials default \\
            --token=\$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) \\
            --kubeconfig=\$KUBECONFIG
        kubectl config set-context default \\
            --cluster=default --user=default \\
            --kubeconfig=\$KUBECONFIG
        kubectl config use-context default --kubeconfig=\$KUBECONFIG
        
        # Get Harbor credentials
        echo "Getting Harbor credentials..."
        kubectl get secret harbor-auth -n arc-systems -o jsonpath='{.data.HARBOR_USERNAME}' | base64 -d > /tmp/harbor_username
        kubectl get secret harbor-auth -n arc-systems -o jsonpath='{.data.HARBOR_PASSWORD}' | base64 -d > /tmp/harbor_password
        kubectl get secret harbor-auth -n arc-systems -o jsonpath='{.data.HARBOR_URL}' | base64 -d > /tmp/harbor_url
        kubectl get secret harbor-auth -n arc-systems -o jsonpath='{.data.HARBOR_PROJECT}' | base64 -d > /tmp/harbor_project
        kubectl get secret ca-key-pair -n cert-manager -o jsonpath='{.data.ca\.crt}' | base64 -d > /tmp/harbor_ca.crt
        
        chmod 600 /tmp/harbor_*
        echo "✅ Harbor credentials retrieved successfully"

    - name: Tag and push images using Docker
      run: |
        echo "=== Tag and push image on self-hosted runner ==="

        HARBOR_USERNAME=\$(cat /tmp/harbor_username)
        HARBOR_PASSWORD=\$(cat /tmp/harbor_password)
        HARBOR_URL="harbor.internal.qroksera.com"
        HARBOR_PROJECT=\$(cat /tmp/harbor_project)
        IMAGE_SHA_TAG="\${{ github.sha }}"
        IMAGE_LATEST_TAG="latest"

        # 内部CAを信頼ストアに追加
        echo "Installing internal CA..."
        sudo cp /tmp/harbor_ca.crt /usr/local/share/ca-certificates/harbor-internal-ca.crt
        sudo update-ca-certificates

        # Docker用のCA設定
        echo "Configuring Docker CA..."
        sudo mkdir -p /etc/docker/certs.d/harbor.internal.qroksera.com
        sudo cp /tmp/harbor_ca.crt /etc/docker/certs.d/harbor.internal.qroksera.com/ca.crt

        # Load済みのローカルimageをHarborタグに付け替える
        docker tag $REPOSITORY_NAME:ci \$HARBOR_URL/\$HARBOR_PROJECT/$REPOSITORY_NAME:\$IMAGE_LATEST_TAG
        docker tag $REPOSITORY_NAME:ci \$HARBOR_URL/\$HARBOR_PROJECT/$REPOSITORY_NAME:\$IMAGE_SHA_TAG

        # /etc/hostsにharbor.internal.qroksera.comを追加
        echo "192.168.122.100 harbor.internal.qroksera.com" | sudo tee -a /etc/hosts

        # Harborにログイン
        echo "Logging in to Harbor..."
        docker login \$HARBOR_URL -u "\$HARBOR_USERNAME" -p "\$HARBOR_PASSWORD"

        # Harborへpush
        echo "Pushing to Harbor..."
        docker push \$HARBOR_URL/\$HARBOR_PROJECT/$REPOSITORY_NAME:\$IMAGE_LATEST_TAG
        docker push \$HARBOR_URL/\$HARBOR_PROJECT/$REPOSITORY_NAME:\$IMAGE_SHA_TAG

        echo "✅ Images pushed successfully to Harbor"
        echo "📦 Pushed tags: \$IMAGE_LATEST_TAG, \$IMAGE_SHA_TAG"

    - name: Cleanup
      if: always()
      run: |
        echo "=== Cleanup ==="
        rm -f /tmp/harbor_* /tmp/kubeconfig /tmp/$REPOSITORY_NAME-image.tar.gz
        echo "✅ Cleanup completed"
WORKFLOW_EOF

# 完了メッセージ
log_status "=== セットアップ完了 ==="
log_status ""
log_status "✅ Runner定義登録:"
log_status "   - $RUNNER_NAME (minRunners=$MIN_RUNNERS, maxRunners=$MAX_RUNNERS)"
log_status "   - リポジトリ: https://github.com/$GITHUB_USERNAME/$REPOSITORY_NAME"
log_status ""
log_status "✅ GitHub Actions workflow作成:"
log_status "   - $WORKFLOW_FILE"
log_status ""
log_status "📝 次のステップ:"
log_status "1. GitHub リポジトリに Commit & Push"
log_status "   git add $WORKFLOW_FILE"
log_status "   git commit -m \"Add GitHub Actions workflow for $REPOSITORY_NAME\""
log_status "   git push"
log_status "2. ArgoCD同期を確認（blog-runner等がSynced/Healthy）"
log_status "3. GitHub ActionsでCI/CDテスト実行"
log_status ""
log_status "🎉 $REPOSITORY_NAME 用のRunner環境が準備完了しました！"
