#!/bin/bash

# GitHub Actions Runner Controller (ARC) - 新しいリポジトリ用Runner追加スクリプト
# 公式GitHub ARC対応版 - クリーンで簡潔な実装

set -euo pipefail

# 共通ライブラリを読み込み
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
source "$SCRIPTS_ROOT/common-k8s-utils.sh"
source "$SCRIPTS_ROOT/common-colors.sh"

# 引数確認
if [[ $# -lt 1 ]]; then
    print_error "使用方法: $0 <repository-name>"
    print_error "例: $0 my-awesome-project"
    exit 1
fi

REPOSITORY_NAME="$1"
# Runner名生成（小文字変換、ドット・アンダースコアをハイフンに変換）
RUNNER_NAME="$(echo "${REPOSITORY_NAME}" | tr '[:upper:]._' '[:lower:]--')-runners"

print_status "=== GitHub Actions Runner追加スクリプト (公式ARC対応) ==="
print_debug "対象リポジトリ: $REPOSITORY_NAME"
print_debug "Runner名: $RUNNER_NAME"

# GitHubユーザー名を取得（settings.tomlから）
SETTINGS_FILE="$SCRIPTS_ROOT/../settings.toml"
if [[ ! -f "$SETTINGS_FILE" ]]; then
    print_error "settings.tomlが見つかりません: $SETTINGS_FILE"
    exit 1
fi

GITHUB_USERNAME=$(grep '^username = ' "$SETTINGS_FILE" | head -1 | cut -d'"' -f2)
if [[ -z "$GITHUB_USERNAME" ]]; then
    print_error "settings.tomlのgithub.usernameが設定されていません"
    exit 1
fi
print_debug "GitHub Username: $GITHUB_USERNAME"

# k8sクラスタ接続確認
print_debug "k8sクラスタ接続確認中..."
if ! ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 k8suser@192.168.122.10 'kubectl get nodes' >/dev/null 2>&1; then
    print_error "k8sクラスタに接続できません"
    exit 1
fi
print_status "✓ k8sクラスタ接続OK"

# GitHub認証情報確認
print_debug "GitHub認証情報確認中..."
if ! ssh -o StrictHostKeyChecking=no k8suser@192.168.122.10 'kubectl get secret github-token -n arc-systems' >/dev/null 2>&1; then
    print_error "GitHub認証情報が見つかりません。make all を実行してください"
    exit 1
fi

# GitHub multi-repo secret確認/作成
print_debug "GitHub multi-repo secret確認中..."
if ! ssh -o StrictHostKeyChecking=no k8suser@192.168.122.10 'kubectl get secret github-multi-repo-secret -n arc-systems' >/dev/null 2>&1; then
    print_debug "github-multi-repo-secret を作成中..."
    GITHUB_TOKEN=$(ssh -o StrictHostKeyChecking=no k8suser@192.168.122.10 'kubectl get secret github-token -n arc-systems -o jsonpath="{.data.github_token}" | base64 -d')
    ssh -o StrictHostKeyChecking=no k8suser@192.168.122.10 "kubectl create secret generic github-multi-repo-secret --from-literal=github_token='$GITHUB_TOKEN' -n arc-systems"
fi

# Runner Scale Set作成
print_status "🏃 RunnerScaleSet作成中..."

# 既存のRunnerを削除（存在する場合）
if ssh -o StrictHostKeyChecking=no k8suser@192.168.122.10 "helm status '$RUNNER_NAME' -n arc-systems" >/dev/null 2>&1; then
    print_warning "既存の $RUNNER_NAME を削除中..."
    ssh -o StrictHostKeyChecking=no k8suser@192.168.122.10 "helm uninstall '$RUNNER_NAME' -n arc-systems"
    sleep 5
fi

# RunnerScaleSetを作成（minRunners=1推奨）
ssh -o StrictHostKeyChecking=no k8suser@192.168.122.10 << EOF
echo "=== RunnerScaleSet '$RUNNER_NAME' を作成中 ==="

helm install $RUNNER_NAME \
  oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set \
  --namespace arc-systems \
  --set githubConfigUrl="https://github.com/$GITHUB_USERNAME/$REPOSITORY_NAME" \
  --set githubConfigSecret="github-multi-repo-secret" \
  --set maxRunners=3 \
  --set minRunners=1 \
  --set containerMode.type=dind \
  --set template.spec.serviceAccountName=github-actions-runner

echo "✓ RunnerScaleSet '$RUNNER_NAME' 作成完了"
EOF

# GitHub Actions workflow作成
print_status "=== GitHub Actions workflow作成 ==="

WORKFLOW_DIR=".github/workflows"
WORKFLOW_FILE="$WORKFLOW_DIR/build-and-push-$REPOSITORY_NAME.yml"

# .github/workflowsディレクトリ作成
mkdir -p "$WORKFLOW_DIR"
print_debug "Workflowディレクトリ作成: $WORKFLOW_DIR"

# workflow.yamlファイル作成
print_debug "Workflowファイル作成中: $WORKFLOW_FILE"
cat > "$WORKFLOW_FILE" << WORKFLOW_EOF
# GitHub Actions workflow for $REPOSITORY_NAME
# Auto-generated by add-runner.sh (公式ARC対応版)

name: Build and Push to Harbor - $REPOSITORY_NAME

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: $RUNNER_NAME  # Kubernetes Runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup kubectl and Harbor credentials
      run: |
        echo "=== Setup kubectl and Harbor credentials ==="
        
        # Install kubectl
        echo "Installing kubectl..."
        curl -LO "https://dl.k8s.io/release/\$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        
        # Configure kubectl for in-cluster access
        echo "Configuring kubectl..."
        export KUBECONFIG=/tmp/kubeconfig
        kubectl config set-cluster default \\
            --server=https://kubernetes.default.svc \\
            --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt \\
            --kubeconfig=\$KUBECONFIG
        kubectl config set-credentials default \\
            --token=\$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) \\
            --kubeconfig=\$KUBECONFIG
        kubectl config set-context default \\
            --cluster=default --user=default \\
            --kubeconfig=\$KUBECONFIG
        kubectl config use-context default --kubeconfig=\$KUBECONFIG
        
        # Get Harbor credentials
        echo "Getting Harbor credentials..."
        kubectl get secret harbor-auth -n arc-systems -o jsonpath='{.data.HARBOR_USERNAME}' | base64 -d > /tmp/harbor_username
        kubectl get secret harbor-auth -n arc-systems -o jsonpath='{.data.HARBOR_PASSWORD}' | base64 -d > /tmp/harbor_password
        kubectl get secret harbor-auth -n arc-systems -o jsonpath='{.data.HARBOR_URL}' | base64 -d > /tmp/harbor_url
        kubectl get secret harbor-auth -n arc-systems -o jsonpath='{.data.HARBOR_PROJECT}' | base64 -d > /tmp/harbor_project
        
        chmod 600 /tmp/harbor_*
        echo "✅ Harbor credentials retrieved successfully"
        
    - name: Build and push images using skopeo
      run: |
        echo "=== Build and push images using skopeo ==="
        
        HARBOR_USERNAME=\$(cat /tmp/harbor_username)
        HARBOR_PASSWORD=\$(cat /tmp/harbor_password)
        HARBOR_URL=\$(cat /tmp/harbor_url)
        HARBOR_PROJECT=\$(cat /tmp/harbor_project)
        
        # Install skopeo
        echo "Installing skopeo..."
        sudo apt-get update && sudo apt-get install -y skopeo
        
        # Build Docker images
        echo "Building Docker images..."
        docker build -t $REPOSITORY_NAME:latest .
        docker build -t $REPOSITORY_NAME:\${{ github.sha }} .
        
        # Push using skopeo
        echo "Pushing to Harbor using skopeo..."
        docker save $REPOSITORY_NAME:latest > /tmp/$REPOSITORY_NAME-latest.tar
        docker save $REPOSITORY_NAME:\${{ github.sha }} > /tmp/$REPOSITORY_NAME-sha.tar
        
        skopeo copy --insecure-policy --dest-tls-verify=false \\
          --dest-creds="\$HARBOR_USERNAME:\$HARBOR_PASSWORD" \\
          docker-archive:/tmp/$REPOSITORY_NAME-latest.tar \\
          docker://\$HARBOR_URL/\$HARBOR_PROJECT/$REPOSITORY_NAME:latest
        
        skopeo copy --insecure-policy --dest-tls-verify=false \\
          --dest-creds="\$HARBOR_USERNAME:\$HARBOR_PASSWORD" \\
          docker-archive:/tmp/$REPOSITORY_NAME-sha.tar \\
          docker://\$HARBOR_URL/\$HARBOR_PROJECT/$REPOSITORY_NAME:\${{ github.sha }}
        
        echo "✅ Images pushed successfully to Harbor"
        
    - name: Cleanup
      if: always()
      run: |
        echo "=== Cleanup ==="
        rm -f /tmp/harbor_* /tmp/kubeconfig /tmp/$REPOSITORY_NAME-*.tar
        echo "✅ Cleanup completed"
WORKFLOW_EOF

# 完了メッセージ
print_status "=== セットアップ完了 ==="
print_status ""
print_status "✅ RunnerScaleSet作成:"
print_status "   - $RUNNER_NAME (minRunners=1, maxRunners=3)"
print_status "   - リポジトリ: https://github.com/$GITHUB_USERNAME/$REPOSITORY_NAME"
print_status ""
print_status "✅ GitHub Actions workflow作成:"
print_status "   - $WORKFLOW_FILE"
print_status ""
print_status "📝 次のステップ:"
print_status "1. GitHub リポジトリに Commit & Push"
print_status "   git add $WORKFLOW_FILE"
print_status "   git commit -m \"Add GitHub Actions workflow for $REPOSITORY_NAME\""
print_status "   git push"
print_status "2. GitHub ActionsでCI/CDテスト実行"
print_status "3. Harborでイメージ確認: http://192.168.122.100"
print_status ""
print_status "🎉 $REPOSITORY_NAME 用のRunner環境が準備完了しました！"